run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - revive
    - misspell
    - gocyclo
    - dupl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
